baseURL = "mikes.tech"
languageCode = "en-us"
title = "Mike Trueba"
theme = "hugo-lithium-theme"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/mktrueba"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/mktrueba"

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"
